/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package testtttttttttttt22;

import edu.esprit.dao.classes.CategorieDAO;
import edu.esprit.dao.classes.PropositionDAO;
import edu.esprit.dao.classes.freelancerdao;
import edu.esprit.dao.classes.proprietairedao;
import edu.esprit.dao.interfaces.ICategorieDAO;
import edu.esprit.dao.interfaces.IFreelancer;
import edu.esprit.dao.interfaces.IProposition;
import edu.esprit.dao.interfaces.Iproprietairedao;
import edu.esprit.entities.Categorie;
import edu.esprit.entities.Proposition;
import edu.esprit.entities.freelancer;
import edu.esprit.entities.proprietaire;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author khalil
 */
public class administrateur_interface extends javax.swing.JFrame {

    /**
     * Creates new form administrateur_interface
     */
    public administrateur_interface() {
        initComponents();
        panel_verrouil.setVisible(false);
        free_gestion.setVisible(false);
        panel_prop.setVisible(false);
        prop_verrou.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nom_cat = new javax.swing.JTextField();
        type_cat = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        ajouter_button = new javax.swing.JButton();
        idcat = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        modifier_button = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        stat = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        prop1 = new javax.swing.JTextField();
        prop2 = new javax.swing.JTextField();
        prop3 = new javax.swing.JTextField();
        prop4 = new javax.swing.JTextField();
        prop5 = new javax.swing.JTextField();
        prop6 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        prop7 = new javax.swing.JTextField();
        prop8 = new javax.swing.JTextField();
        prop9 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        general_panel = new javax.swing.JPanel();
        free_gestion = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        supprime_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        oui_button = new javax.swing.JButton();
        panel_verrouil = new javax.swing.JPanel();
        ver_button = new javax.swing.JButton();
        verr_button = new javax.swing.JButton();
        retour_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        prenom_text = new javax.swing.JTextField();
        nom_text = new javax.swing.JTextField();
        email_text = new javax.swing.JTextField();
        pays_text = new javax.swing.JTextField();
        ville_text = new javax.swing.JTextField();
        login_text = new javax.swing.JTextField();
        pwd_text = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        statut_text = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        id_text = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        panel_trois_boutton = new javax.swing.JPanel();
        free_button = new javax.swing.JButton();
        prop_button = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        panel_prop = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table3_1 = new javax.swing.JTable();
        supprime_prop = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        prop_verrou = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        id_text_prop = new javax.swing.JTextField();
        prenom_text_prop = new javax.swing.JTextField();
        nom_text_prop = new javax.swing.JTextField();
        email_text_prop = new javax.swing.JTextField();
        pays_text_prop = new javax.swing.JTextField();
        ville_text_prop = new javax.swing.JTextField();
        login_text_prop = new javax.swing.JTextField();
        pwd_text_prop = new javax.swing.JTextField();
        entrp_text_prop = new javax.swing.JTextField();
        statut_text_prop = new javax.swing.JTextField();
        retour_prop_button = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setOpaque(false);

        jScrollPane1.setOpaque(false);

        table1.setModel(new ListCategories());
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jScrollPane1.setBounds(20, 80, 452, 150);
        jDesktopPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom :");
        jLabel2.setBounds(520, 160, 50, 19);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Type :");
        jLabel3.setBounds(520, 210, 50, 19);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nom_cat.setOpaque(false);
        nom_cat.setBounds(590, 150, 150, 30);
        jDesktopPane1.add(nom_cat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        type_cat.setOpaque(false);
        type_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_catActionPerformed(evt);
            }
        });
        type_cat.setBounds(590, 200, 150, 30);
        jDesktopPane1.add(type_cat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel26.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Id:");
        jLabel26.setBounds(520, 100, 40, 30);
        jDesktopPane1.add(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ajouter_button.setBackground(new java.awt.Color(0, 147, 204));
        ajouter_button.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        ajouter_button.setForeground(new java.awt.Color(255, 255, 255));
        ajouter_button.setText("Ajouter");
        ajouter_button.setOpaque(false);
        ajouter_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter_buttonActionPerformed(evt);
            }
        });
        ajouter_button.setBounds(140, 363, 90, 30);
        jDesktopPane1.add(ajouter_button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        idcat.setOpaque(false);
        idcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcatActionPerformed(evt);
            }
        });
        idcat.setBounds(590, 100, 150, 30);
        jDesktopPane1.add(idcat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setBackground(new java.awt.Color(0, 147, 204));
        jButton2.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Supprimer");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(330, 363, 103, 30);
        jDesktopPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        modifier_button.setBackground(new java.awt.Color(0, 147, 204));
        modifier_button.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        modifier_button.setForeground(new java.awt.Color(255, 255, 255));
        modifier_button.setText("Modifier");
        modifier_button.setOpaque(false);
        modifier_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifier_buttonActionPerformed(evt);
            }
        });
        modifier_button.setBounds(530, 363, 90, 30);
        jDesktopPane1.add(modifier_button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\testtttttttttttt22\\src\\testtttttttttttt22\\bloggif_545a8f2c50044.jpeg")); // NOI18N
        jLabel24.setBounds(0, 0, 788, 510);
        jDesktopPane1.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane2.addTab("Gestion Categories", jDesktopPane1);

        jDesktopPane2.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane2.setOpaque(false);

        stat.setOpaque(false);
        stat.setBounds(480, 410, 160, 30);
        jDesktopPane2.add(stat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel28.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Statut:");
        jLabel28.setBounds(380, 410, 60, 30);
        jDesktopPane2.add(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton8.setBackground(new java.awt.Color(0, 147, 204));
        jButton8.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Valider");
        jButton8.setOpaque(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.setBounds(670, 410, 90, 30);
        jDesktopPane2.add(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel32.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("id:");
        jLabel32.setBounds(70, 250, 18, 19);
        jDesktopPane2.add(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel33.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("titre:");
        jLabel33.setBounds(70, 290, 35, 19);
        jDesktopPane2.add(jLabel33, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel34.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("description:");
        jLabel34.setBounds(70, 330, 90, 20);
        jDesktopPane2.add(jLabel34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel35.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("duree_estimee:");
        jLabel35.setBounds(70, 370, 101, 30);
        jDesktopPane2.add(jLabel35, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel36.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("date_debut:");
        jLabel36.setBounds(70, 420, 79, 19);
        jDesktopPane2.add(jLabel36, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel37.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("date_fin:");
        jLabel37.setBounds(370, 250, 60, 19);
        jDesktopPane2.add(jLabel37, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel38.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("budget:");
        jLabel38.setBounds(370, 290, 51, 19);
        jDesktopPane2.add(jLabel38, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel39.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("categorie:");
        jLabel39.setBounds(370, 330, 67, 19);
        jDesktopPane2.add(jLabel39, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel40.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("competences:");
        jLabel40.setBounds(370, 370, 91, 19);
        jDesktopPane2.add(jLabel40, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prop1.setOpaque(false);
        prop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prop1ActionPerformed(evt);
            }
        });
        prop1.setBounds(180, 240, 120, 30);
        jDesktopPane2.add(prop1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prop2.setOpaque(false);
        prop2.setBounds(180, 280, 120, 30);
        jDesktopPane2.add(prop2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prop3.setOpaque(false);
        prop3.setBounds(180, 320, 120, 30);
        jDesktopPane2.add(prop3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prop4.setOpaque(false);
        prop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prop4ActionPerformed(evt);
            }
        });
        prop4.setBounds(180, 370, 120, 30);
        jDesktopPane2.add(prop4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prop5.setOpaque(false);
        prop5.setBounds(180, 420, 120, 30);
        jDesktopPane2.add(prop5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prop6.setOpaque(false);
        prop6.setBounds(480, 240, 140, 30);
        jDesktopPane2.add(prop6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane5.setOpaque(false);

        table2.setModel(new ListProposition());
        table2.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt){
                table2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(table2);

        jScrollPane5.setBounds(50, 20, 452, 180);
        jDesktopPane2.add(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prop7.setOpaque(false);
        prop7.setBounds(480, 290, 140, 30);
        jDesktopPane2.add(prop7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prop8.setOpaque(false);
        prop8.setBounds(480, 330, 140, 30);
        jDesktopPane2.add(prop8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prop9.setOpaque(false);
        prop9.setBounds(480, 370, 140, 30);
        jDesktopPane2.add(prop9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\testtttttttttttt22\\src\\testtttttttttttt22\\bloggif_545a8f2c50044.jpeg")); // NOI18N
        jLabel25.setBounds(0, 0, 788, 510);
        jDesktopPane2.add(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane2.addTab("Gestion Offres d'emplois", jDesktopPane2);

        jDesktopPane3.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane3.setOpaque(false);

        general_panel.setOpaque(false);
        general_panel.setLayout(null);

        free_gestion.setOpaque(false);
        free_gestion.setLayout(null);

        jScrollPane3.setOpaque(false);

        table3.setModel(new ListUsers());
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table3);

        free_gestion.add(jScrollPane3);
        jScrollPane3.setBounds(12, 65, 506, 160);

        supprime_button.setText("Supprimer");
        supprime_button.setOpaque(false);
        supprime_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprime_buttonActionPerformed(evt);
            }
        });
        free_gestion.add(supprime_button);
        supprime_button.setBounds(30, 280, 81, 23);

        jLabel1.setText("Verrouiller/Deverrouiller ?");
        free_gestion.add(jLabel1);
        jLabel1.setBounds(190, 240, 121, 14);

        oui_button.setText("Oui");
        oui_button.setOpaque(false);
        oui_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oui_buttonActionPerformed(evt);
            }
        });
        free_gestion.add(oui_button);
        oui_button.setBounds(240, 280, 49, 23);

        panel_verrouil.setOpaque(false);

        ver_button.setText("Deverrouiller");
        ver_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_buttonActionPerformed(evt);
            }
        });

        verr_button.setText("Verrouiller");
        verr_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verr_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_verrouilLayout = new javax.swing.GroupLayout(panel_verrouil);
        panel_verrouil.setLayout(panel_verrouilLayout);
        panel_verrouilLayout.setHorizontalGroup(
            panel_verrouilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_verrouilLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panel_verrouilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(verr_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ver_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panel_verrouilLayout.setVerticalGroup(
            panel_verrouilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_verrouilLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ver_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(verr_button)
                .addGap(29, 29, 29))
        );

        free_gestion.add(panel_verrouil);
        panel_verrouil.setBounds(160, 320, 190, 150);

        retour_button.setText("Retour");
        retour_button.setOpaque(false);
        retour_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour_buttonActionPerformed(evt);
            }
        });
        free_gestion.add(retour_button);
        retour_button.setBounds(700, 450, 65, 23);

        jLabel4.setText("Prenom :");
        free_gestion.add(jLabel4);
        jLabel4.setBounds(550, 30, 60, 14);

        jLabel5.setText("Nom :");
        free_gestion.add(jLabel5);
        jLabel5.setBounds(550, 70, 41, 14);

        jLabel6.setText("Email :");
        free_gestion.add(jLabel6);
        jLabel6.setBounds(550, 110, 41, 14);

        jLabel7.setText("Password :");
        free_gestion.add(jLabel7);
        jLabel7.setBounds(550, 280, 70, 14);

        jLabel8.setText("Pays :");
        free_gestion.add(jLabel8);
        jLabel8.setBounds(550, 160, 41, 14);

        jLabel9.setText("Ville :");
        free_gestion.add(jLabel9);
        jLabel9.setBounds(550, 200, 25, 14);

        jLabel10.setText("Login :");
        free_gestion.add(jLabel10);
        jLabel10.setBounds(550, 240, 41, 14);

        prenom_text.setOpaque(false);
        free_gestion.add(prenom_text);
        prenom_text.setBounds(650, 30, 100, 20);

        nom_text.setOpaque(false);
        free_gestion.add(nom_text);
        nom_text.setBounds(650, 70, 100, 20);

        email_text.setOpaque(false);
        free_gestion.add(email_text);
        email_text.setBounds(650, 110, 100, 20);

        pays_text.setOpaque(false);
        free_gestion.add(pays_text);
        pays_text.setBounds(650, 160, 100, 20);

        ville_text.setOpaque(false);
        free_gestion.add(ville_text);
        ville_text.setBounds(650, 200, 100, 20);

        login_text.setOpaque(false);
        free_gestion.add(login_text);
        login_text.setBounds(650, 240, 100, 20);

        pwd_text.setOpaque(false);
        free_gestion.add(pwd_text);
        pwd_text.setBounds(650, 280, 100, 20);

        jLabel11.setText("Statut :");
        free_gestion.add(jLabel11);
        jLabel11.setBounds(550, 320, 37, 14);

        statut_text.setOpaque(false);
        free_gestion.add(statut_text);
        statut_text.setBounds(650, 320, 100, 20);

        jLabel12.setText("ID :");
        free_gestion.add(jLabel12);
        jLabel12.setBounds(550, 0, 18, 14);

        id_text.setOpaque(false);
        free_gestion.add(id_text);
        id_text.setBounds(650, 0, 100, 20);

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\testtttttttttttt22\\src\\testtttttttttttt22\\bloggif_545a8f2c50044.jpeg")); // NOI18N
        free_gestion.add(jLabel31);
        jLabel31.setBounds(0, 0, 788, 513);

        general_panel.add(free_gestion);
        free_gestion.setBounds(0, 0, 780, 480);

        panel_trois_boutton.setOpaque(false);
        panel_trois_boutton.setLayout(null);

        free_button.setText("Freelancer");
        free_button.setOpaque(false);
        free_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                free_buttonActionPerformed(evt);
            }
        });
        panel_trois_boutton.add(free_button);
        free_button.setBounds(0, 0, 0, 0);

        prop_button.setText("Propriétaire");
        prop_button.setOpaque(false);
        prop_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prop_buttonActionPerformed(evt);
            }
        });
        panel_trois_boutton.add(prop_button);
        prop_button.setBounds(0, 0, 0, 0);

        jButton10.setText("Sous Administrateur");
        jButton10.setOpaque(false);
        panel_trois_boutton.add(jButton10);
        jButton10.setBounds(0, 0, 0, 0);

        general_panel.add(panel_trois_boutton);
        panel_trois_boutton.setBounds(220, 120, 400, 270);

        panel_prop.setOpaque(false);
        panel_prop.setLayout(null);

        jScrollPane2.setOpaque(false);

        table3_1.setModel(new Listprop());
        table3_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3_1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table3_1);

        panel_prop.add(jScrollPane2);
        jScrollPane2.setBounds(20, 68, 452, 120);

        supprime_prop.setText("Supprimer");
        supprime_prop.setOpaque(false);
        supprime_prop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprime_propActionPerformed(evt);
            }
        });
        panel_prop.add(supprime_prop);
        supprime_prop.setBounds(20, 233, 81, 23);

        jLabel13.setText("Deverrouiller/Verouiller ?");
        panel_prop.add(jLabel13);
        jLabel13.setBounds(209, 233, 117, 14);

        jButton5.setText("Oui");
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel_prop.add(jButton5);
        jButton5.setBounds(255, 276, 49, 23);

        prop_verrou.setOpaque(false);
        prop_verrou.setLayout(null);

        jButton6.setText("Deverrouiller");
        jButton6.setOpaque(false);
        prop_verrou.add(jButton6);
        jButton6.setBounds(12, 29, 93, 23);

        jButton7.setText("Verrouiller");
        jButton7.setOpaque(false);
        prop_verrou.add(jButton7);
        jButton7.setBounds(12, 93, 105, 23);

        panel_prop.add(prop_verrou);
        prop_verrou.setBounds(210, 310, 150, 150);

        jLabel14.setText("Id :");
        panel_prop.add(jLabel14);
        jLabel14.setBounds(530, 30, 17, 14);

        jLabel15.setText("Prenom :");
        panel_prop.add(jLabel15);
        jLabel15.setBounds(530, 80, 43, 14);

        jLabel16.setText("Nom :");
        panel_prop.add(jLabel16);
        jLabel16.setBounds(530, 120, 28, 14);

        jLabel17.setText("Email :");
        panel_prop.add(jLabel17);
        jLabel17.setBounds(530, 180, 31, 14);

        jLabel18.setText("Pays :");
        panel_prop.add(jLabel18);
        jLabel18.setBounds(530, 230, 30, 14);

        jLabel19.setText("Ville :");
        panel_prop.add(jLabel19);
        jLabel19.setBounds(530, 280, 25, 14);

        jLabel20.setText("Login :");
        panel_prop.add(jLabel20);
        jLabel20.setBounds(530, 330, 32, 14);

        jLabel21.setText("Password :");
        panel_prop.add(jLabel21);
        jLabel21.setBounds(530, 380, 70, 14);

        jLabel22.setText("Nom Entreprise :");
        panel_prop.add(jLabel22);
        jLabel22.setBounds(520, 410, 100, 14);

        jLabel23.setText("Statut :");
        panel_prop.add(jLabel23);
        jLabel23.setBounds(530, 450, 37, 14);

        id_text_prop.setOpaque(false);
        panel_prop.add(id_text_prop);
        id_text_prop.setBounds(630, 20, 120, 20);

        prenom_text_prop.setOpaque(false);
        panel_prop.add(prenom_text_prop);
        prenom_text_prop.setBounds(630, 70, 120, 20);

        nom_text_prop.setOpaque(false);
        panel_prop.add(nom_text_prop);
        nom_text_prop.setBounds(630, 120, 120, 20);

        email_text_prop.setOpaque(false);
        panel_prop.add(email_text_prop);
        email_text_prop.setBounds(630, 170, 120, 20);

        pays_text_prop.setOpaque(false);
        panel_prop.add(pays_text_prop);
        pays_text_prop.setBounds(630, 220, 120, 20);

        ville_text_prop.setOpaque(false);
        panel_prop.add(ville_text_prop);
        ville_text_prop.setBounds(630, 270, 120, 20);

        login_text_prop.setOpaque(false);
        panel_prop.add(login_text_prop);
        login_text_prop.setBounds(630, 320, 120, 20);

        pwd_text_prop.setOpaque(false);
        panel_prop.add(pwd_text_prop);
        pwd_text_prop.setBounds(630, 370, 120, 20);

        entrp_text_prop.setOpaque(false);
        panel_prop.add(entrp_text_prop);
        entrp_text_prop.setBounds(630, 410, 120, 20);

        statut_text_prop.setOpaque(false);
        panel_prop.add(statut_text_prop);
        statut_text_prop.setBounds(630, 440, 120, 20);

        retour_prop_button.setText("Retour");
        retour_prop_button.setOpaque(false);
        retour_prop_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour_prop_buttonActionPerformed(evt);
            }
        });
        panel_prop.add(retour_prop_button);
        retour_prop_button.setBounds(10, 450, 65, 23);

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\testtttttttttttt22\\src\\testtttttttttttt22\\bloggif_545a8f2c50044.jpeg")); // NOI18N
        panel_prop.add(jLabel30);
        jLabel30.setBounds(0, 0, 788, 513);

        general_panel.add(panel_prop);
        panel_prop.setBounds(0, 0, 780, 480);

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\testtttttttttttt22\\src\\testtttttttttttt22\\bloggif_545a8f2c50044.jpeg")); // NOI18N
        general_panel.add(jLabel29);
        jLabel29.setBounds(0, 0, 788, 513);

        general_panel.setBounds(0, 0, 780, 480);
        jDesktopPane3.add(general_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane2.addTab("Gestion des Comptes utilisateurs ", jDesktopPane3);

        jDesktopPane4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\testtttttttttttt22\\src\\testtttttttttttt22\\bloggif_545a8f2c50044.jpeg")); // NOI18N
        jLabel27.setBounds(0, 0, 788, 510);
        jDesktopPane4.add(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane2.addTab("Verifier statistique", jDesktopPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked

        int row = table1.getSelectedRow();
      
       idcat.setText(table1.getModel().getValueAt(row, 0).toString());
        nom_cat.setText(table1.getModel().getValueAt(row, 1).toString());
        type_cat.setText(table1.getModel().getValueAt(row, 2).toString());
        
    }//GEN-LAST:event_table1MouseClicked
 private void table2MouseClicked(java.awt.event.MouseEvent evt) {                                    

        int row = table2.getSelectedRow();
        
        
        prop1.setText(table2.getModel().getValueAt(row, 0).toString());
        prop2.setText(table2.getModel().getValueAt(row, 1).toString());
        prop3.setText(table2.getModel().getValueAt(row, 2).toString());
        prop4.setText(table2.getModel().getValueAt(row, 3).toString());
        prop5.setText(table2.getModel().getValueAt(row, 4).toString());
        prop6.setText(table2.getModel().getValueAt(row, 5).toString());
        prop7.setText(table2.getModel().getValueAt(row, 6).toString());
        prop8.setText(table2.getModel().getValueAt(row, 7).toString());
        prop9.setText(table2.getModel().getValueAt(row, 8).toString());
        stat.setText(table2.getModel().getValueAt(row,  9).toString());
        
        
    }  
    private void ajouter_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter_buttonActionPerformed
        Categorie cat=new Categorie();
         int x;
        x=Integer.parseInt(idcat.getText());
        cat.setNom(nom_cat.getText());
        cat.setType(type_cat.getText());
        
            ICategorieDAO catdao= new CategorieDAO();
            catdao.save( cat);
            JOptionPane.showMessageDialog(null, "Insertion Reuissite -__-");
           table1.setModel(new ListCategories());
    }//GEN-LAST:event_ajouter_buttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       ICategorieDAO cat_dao=new CategorieDAO();
        int x;
        x=Integer.parseInt(idcat.getText());
        String type=type_cat.getText();
        String nom=nom_cat.getText();
        Categorie categ=new Categorie(x,nom, type);
        cat_dao.delete(categ);
        table1.setModel(new ListCategories());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void modifier_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifier_buttonActionPerformed
         String nom=nom_cat.getText();
      String type=type_cat.getText();int x;
        x=Integer.parseInt(idcat.getText());
      
      Categorie cat=new Categorie(x,nom,type);

      
     ICategorieDAO catdao= new CategorieDAO();
            
      catdao.update(cat);
    
      table1.setModel(new ListCategories());
    }//GEN-LAST:event_modifier_buttonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         IProposition prop= new PropositionDAO();
           int x;
        x=Integer.parseInt(prop1.getText());
        String a=prop2.getText();
        String b=prop3.getText();
        String c=prop4.getText();
        String d=prop5.getText();
        String e=prop6.getText();
        float y;
        y=Float.parseFloat(prop7.getText());
   String f=prop8.getText();
      String g=prop9.getText();
        String h=stat.getText();
        Categorie cat = new Categorie();
        ICategorieDAO catdao = new CategorieDAO();
        cat=catdao.findByNom(f);
    Proposition p=new Proposition(x,a, b,c,d,e,y,cat,g,h);
    prop.update(p);
     
      table2.setModel(new ListProposition());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseClicked
       int row = table3.getSelectedRow();
        id_text.setText(table3.getModel().getValueAt(row, 0).toString());
        prenom_text.setText(table3.getModel().getValueAt(row, 1).toString());
        nom_text.setText(table3.getModel().getValueAt(row, 2).toString());
        email_text.setText(table3.getModel().getValueAt(row, 3).toString());
        pays_text.setText(table3.getModel().getValueAt(row, 4).toString());
        ville_text.setText(table3.getModel().getValueAt(row, 5).toString());
        login_text.setText(table3.getModel().getValueAt(row, 6).toString());
        pwd_text.setText(table3.getModel().getValueAt(row, 7).toString());
        statut_text.setText(table3.getModel().getValueAt(row, 8).toString());
    }//GEN-LAST:event_table3MouseClicked

    private void supprime_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprime_buttonActionPerformed

        IFreelancer freedao = new freelancerdao();
        String id = id_text.getText();
        String prenom = prenom_text.getText();
        String nom = nom_text.getText();
        String email = email_text.getText();
        String pays = pays_text.getText();
        String ville = ville_text.getText();
        String login = login_text.getText();
        String pwd = pwd_text.getText();
        String statut = statut_text.getText();
        freelancer free = new freelancer();
        int idr = Integer.parseInt(id);
        free.setId(idr);
        free.setPrenom(prenom);
        free.setNom(nom);
        free.setEmail(email);
        free.setPays(pays);
        free.setVille(ville);
        free.setLogin(login);
        free.setPwd(pwd);
        free.setStatus(statut);

        freedao.delete(free);
        table3.setModel(new ListUsers());
    }//GEN-LAST:event_supprime_buttonActionPerformed

    private void oui_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oui_buttonActionPerformed
        general_panel.setVisible(true);
        panel_trois_boutton.setVisible(false);
        panel_verrouil.setVisible(true);
    }//GEN-LAST:event_oui_buttonActionPerformed

    private void ver_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_buttonActionPerformed
        IFreelancer freedao = new freelancerdao();
        String id = id_text.getText();
        String prenom = prenom_text.getText();
        String nom = nom_text.getText();
        String email = email_text.getText();
        String pays = pays_text.getText();
        String ville = ville_text.getText();
        String login = login_text.getText();
        String pwd = pwd_text.getText();
        String statut = statut_text.getText();
        freelancer free = new freelancer();
        int idr = Integer.parseInt(id);
        free.setId(idr);
        free.setPrenom(prenom);
        free.setNom(nom);
        free.setEmail(email);
        free.setPays(pays);
        free.setVille(ville);
        free.setLogin(login);
        free.setPwd(pwd);
        free.setStatus(statut);

        freedao.update_actif(free);
        table3.setModel(new ListUsers());
    }//GEN-LAST:event_ver_buttonActionPerformed

    private void verr_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verr_buttonActionPerformed
        IFreelancer freedao = new freelancerdao();
        String id = id_text.getText();
        String prenom = prenom_text.getText();
        String nom = nom_text.getText();
        String email = email_text.getText();
        String pays = pays_text.getText();
        String ville = ville_text.getText();
        String login = login_text.getText();
        String pwd = pwd_text.getText();
        String statut = statut_text.getText();
        freelancer free = new freelancer();
        int idr = Integer.parseInt(id);
        free.setId(idr);
        free.setPrenom(prenom);
        free.setNom(nom);
        free.setEmail(email);
        free.setPays(pays);
        free.setVille(ville);
        free.setLogin(login);
        free.setPwd(pwd);
        free.setStatus(statut);

        freedao.update_nonactif(free);
        table3.setModel(new ListUsers());
    }//GEN-LAST:event_verr_buttonActionPerformed

    private void retour_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour_buttonActionPerformed
        general_panel.setVisible(true);
        panel_trois_boutton.setVisible(true);
        panel_verrouil.setVisible(false);
        panel_verrouil.setVisible(false);
        general_panel.removeAll();
        general_panel.repaint();
        general_panel.revalidate();
        general_panel.add(panel_trois_boutton);
        general_panel.repaint();
        general_panel.revalidate();
    }//GEN-LAST:event_retour_buttonActionPerformed

    private void free_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_free_buttonActionPerformed
        general_panel.setVisible(true);
        panel_trois_boutton.setVisible(false);
        panel_verrouil.setVisible(false);
        free_gestion.setVisible(true);
        general_panel.removeAll();
        general_panel.repaint();
        general_panel.revalidate();
        general_panel.add(free_gestion);
        general_panel.repaint();
        general_panel.revalidate();
    }//GEN-LAST:event_free_buttonActionPerformed

    private void prop_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prop_buttonActionPerformed
        general_panel.setVisible(true);
        panel_trois_boutton.setVisible(false);
        panel_verrouil.setVisible(false);
        free_gestion.setVisible(false);
        panel_prop.setVisible(true);
        prop_verrou.setVisible(false);
        general_panel.removeAll();
        general_panel.repaint();
        general_panel.revalidate();
        general_panel.add(panel_prop);
        general_panel.repaint();
        general_panel.revalidate();
    }//GEN-LAST:event_prop_buttonActionPerformed

    private void table3_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3_1MouseClicked
        int row = table3_1.getSelectedRow();
        id_text_prop.setText(table3_1.getModel().getValueAt(row, 0).toString());
        prenom_text_prop.setText(table3_1.getModel().getValueAt(row, 1).toString());
        nom_text_prop.setText(table3_1.getModel().getValueAt(row, 2).toString());
        email_text_prop.setText(table3_1.getModel().getValueAt(row, 3).toString());
        pays_text_prop.setText(table3_1.getModel().getValueAt(row, 4).toString());
        ville_text_prop.setText(table3_1.getModel().getValueAt(row, 5).toString());
        login_text_prop.setText(table3_1.getModel().getValueAt(row, 6).toString());
        pwd_text_prop.setText(table3_1.getModel().getValueAt(row, 7).toString());
        entrp_text_prop.setText(table3_1.getModel().getValueAt(row, 7).toString());
        statut_text_prop.setText(table3_1.getModel().getValueAt(row, 9).toString());
    }//GEN-LAST:event_table3_1MouseClicked

    private void supprime_propActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprime_propActionPerformed

        Iproprietairedao freedao = new proprietairedao();
        String id = id_text_prop.getText();
        String prenom = prenom_text_prop.getText();
        String nom = nom_text_prop.getText();
        String email = email_text_prop.getText();
        String pays = pays_text_prop.getText();
        String ville = ville_text_prop.getText();
        String login = login_text_prop.getText();
        String pwd = pwd_text_prop.getText();
        String statut = statut_text_prop.getText();
        String entre = entrp_text_prop.getText();
        proprietaire free = new proprietaire();
        int idr = Integer.parseInt(id);
        free.setId(idr);
        free.setPrenom(prenom);
        free.setNom(nom);
        free.setEmail(email);
        free.setPays(pays);
        free.setVille(ville);
        free.setLogin(login);
        free.setPwd(pwd);
        free.setStatut(statut);
        free.setEntrep(entre);

        freedao.delete(free);
        table3.setModel(new Listprop());
    }//GEN-LAST:event_supprime_propActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        prop_verrou.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void retour_prop_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour_prop_buttonActionPerformed
        general_panel.setVisible(true);
        panel_trois_boutton.setVisible(true);
        panel_verrouil.setVisible(false);
        panel_verrouil.setVisible(false);
        general_panel.removeAll();
        general_panel.repaint();
        general_panel.revalidate();
        general_panel.add(panel_trois_boutton);
        general_panel.repaint();
        general_panel.revalidate();
    }//GEN-LAST:event_retour_prop_buttonActionPerformed

    private void type_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type_catActionPerformed

    private void idcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcatActionPerformed

    private void prop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prop1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prop1ActionPerformed

    private void prop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prop4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prop4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administrateur_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administrateur_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administrateur_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administrateur_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administrateur_interface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter_button;
    private javax.swing.JTextField email_text;
    private javax.swing.JTextField email_text_prop;
    private javax.swing.JTextField entrp_text_prop;
    private javax.swing.JButton free_button;
    private javax.swing.JPanel free_gestion;
    private javax.swing.JPanel general_panel;
    private javax.swing.JTextField id_text;
    private javax.swing.JTextField id_text_prop;
    private javax.swing.JTextField idcat;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField login_text;
    private javax.swing.JTextField login_text_prop;
    private javax.swing.JButton modifier_button;
    private javax.swing.JTextField nom_cat;
    private javax.swing.JTextField nom_text;
    private javax.swing.JTextField nom_text_prop;
    private javax.swing.JButton oui_button;
    private javax.swing.JPanel panel_prop;
    private javax.swing.JPanel panel_trois_boutton;
    private javax.swing.JPanel panel_verrouil;
    private javax.swing.JTextField pays_text;
    private javax.swing.JTextField pays_text_prop;
    private javax.swing.JTextField prenom_text;
    private javax.swing.JTextField prenom_text_prop;
    private javax.swing.JTextField prop1;
    private javax.swing.JTextField prop2;
    private javax.swing.JTextField prop3;
    private javax.swing.JTextField prop4;
    private javax.swing.JTextField prop5;
    private javax.swing.JTextField prop6;
    private javax.swing.JTextField prop7;
    private javax.swing.JTextField prop8;
    private javax.swing.JTextField prop9;
    private javax.swing.JButton prop_button;
    private javax.swing.JPanel prop_verrou;
    private javax.swing.JTextField pwd_text;
    private javax.swing.JTextField pwd_text_prop;
    private javax.swing.JButton retour_button;
    private javax.swing.JButton retour_prop_button;
    private javax.swing.JTextField stat;
    private javax.swing.JTextField statut_text;
    private javax.swing.JTextField statut_text_prop;
    private javax.swing.JButton supprime_button;
    private javax.swing.JButton supprime_prop;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTable table3_1;
    private javax.swing.JTextField type_cat;
    private javax.swing.JButton ver_button;
    private javax.swing.JButton verr_button;
    private javax.swing.JTextField ville_text;
    private javax.swing.JTextField ville_text_prop;
    // End of variables declaration//GEN-END:variables
}
