/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package testtttttttttttt22;

import edu.esprit.dao.classes.Administrateurdao;
import edu.esprit.dao.classes.freelancerdao;
import edu.esprit.dao.classes.proprietairedao;
import edu.esprit.dao.interfaces.IFreelancer;
import edu.esprit.entities.administrateur;
import edu.esprit.entities.freelancer;
import edu.esprit.entities.proprietaire;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author khalil
 */
public class premiere_page extends javax.swing.JFrame {

    /**  
     * Creates new form premiere_page
     */
    
    public premiere_page() {
        initComponents();
        deux_button_panel.setVisible(true);
        free_insc_panel.setVisible(false);
        chix_panel.setVisible(false);
        prop_insc_panel.setVisible(false);
        premier_pas_panel.setVisible(true);
         deux_button_panel.removeAll();
            deux_button_panel.repaint();
            deux_button_panel.revalidate();
            deux_button_panel.add(premier_pas_panel);
            deux_button_panel.repaint();
            deux_button_panel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        body1 = new javax.swing.JPanel();
        inscr_button = new javax.swing.JButton();
        conn_button = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        deux_button_panel = new javax.swing.JPanel();
        free_insc_panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        prenom_text_free = new javax.swing.JTextField();
        nom_text_free = new javax.swing.JTextField();
        email_text_free = new javax.swing.JTextField();
        pays_text_free = new javax.swing.JTextField();
        ville_text_free = new javax.swing.JTextField();
        log_text_free = new javax.swing.JTextField();
        pwd_text_free = new javax.swing.JPasswordField();
        inscrire_button = new javax.swing.JButton();
        chix_panel = new javax.swing.JPanel();
        free_button = new javax.swing.JButton();
        prop_button = new javax.swing.JButton();
        prop_insc_panel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        prenom_insc_prop = new javax.swing.JTextField();
        nom_insc_prop = new javax.swing.JTextField();
        email_insc_prop = new javax.swing.JTextField();
        pays_insc_prop = new javax.swing.JTextField();
        ville_insc_prop = new javax.swing.JTextField();
        log_insc_prop = new javax.swing.JTextField();
        entrep_insc_prop = new javax.swing.JTextField();
        pwd_insc_prop = new javax.swing.JPasswordField();
        incrire_button_prop = new javax.swing.JButton();
        premier_pas_panel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        log_text = new javax.swing.JTextField();
        pwd_text = new javax.swing.JTextField();
        type_text = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        body.setLayout(null);

        body1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        body1.setOpaque(false);

        inscr_button.setBackground(new java.awt.Color(0, 147, 204));
        inscr_button.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        inscr_button.setForeground(new java.awt.Color(0, 0, 51));
        inscr_button.setText("Inscription");
        inscr_button.setOpaque(false);
        inscr_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscr_buttonActionPerformed(evt);
            }
        });

        conn_button.setBackground(new java.awt.Color(0, 147, 204));
        conn_button.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        conn_button.setForeground(new java.awt.Color(0, 0, 51));
        conn_button.setText("Connexion");
        conn_button.setOpaque(false);
        conn_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conn_buttonActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 147, 204));
        jButton3.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 51));
        jButton3.setText("Consulter ");
        jButton3.setOpaque(false);

        javax.swing.GroupLayout body1Layout = new javax.swing.GroupLayout(body1);
        body1.setLayout(body1Layout);
        body1Layout.setHorizontalGroup(
            body1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conn_button, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
            .addComponent(inscr_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        body1Layout.setVerticalGroup(
            body1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(conn_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inscr_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        body.add(body1);
        body1.setBounds(0, 0, 160, 510);

        deux_button_panel.setOpaque(false);
        deux_button_panel.setLayout(null);

        free_insc_panel.setOpaque(false);
        free_insc_panel.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prenom :");
        free_insc_panel.add(jLabel4);
        jLabel4.setBounds(12, 24, 57, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nom :");
        free_insc_panel.add(jLabel5);
        jLabel5.setBounds(12, 77, 37, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email :");
        free_insc_panel.add(jLabel6);
        jLabel6.setBounds(12, 130, 44, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pays :");
        free_insc_panel.add(jLabel7);
        jLabel7.setBounds(12, 183, 37, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ville :");
        free_insc_panel.add(jLabel8);
        jLabel8.setBounds(12, 242, 38, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Login :");
        free_insc_panel.add(jLabel9);
        jLabel9.setBounds(12, 292, 44, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mot de passe :");
        free_insc_panel.add(jLabel10);
        jLabel10.setBounds(12, 348, 88, 17);

        prenom_text_free.setOpaque(false);
        free_insc_panel.add(prenom_text_free);
        prenom_text_free.setBounds(132, 21, 160, 30);

        nom_text_free.setOpaque(false);
        free_insc_panel.add(nom_text_free);
        nom_text_free.setBounds(132, 64, 160, 30);

        email_text_free.setOpaque(false);
        free_insc_panel.add(email_text_free);
        email_text_free.setBounds(132, 117, 160, 30);

        pays_text_free.setOpaque(false);
        free_insc_panel.add(pays_text_free);
        pays_text_free.setBounds(132, 170, 160, 30);

        ville_text_free.setOpaque(false);
        free_insc_panel.add(ville_text_free);
        ville_text_free.setBounds(132, 229, 160, 30);

        log_text_free.setOpaque(false);
        free_insc_panel.add(log_text_free);
        log_text_free.setBounds(132, 279, 160, 30);

        pwd_text_free.setOpaque(false);
        free_insc_panel.add(pwd_text_free);
        pwd_text_free.setBounds(132, 335, 160, 30);

        inscrire_button.setText("Inscrire");
        inscrire_button.setOpaque(false);
        inscrire_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrire_buttonActionPerformed(evt);
            }
        });
        free_insc_panel.add(inscrire_button);
        inscrire_button.setBounds(237, 442, 69, 23);

        chix_panel.setOpaque(false);
        chix_panel.setLayout(null);

        free_button.setBackground(new java.awt.Color(0, 147, 204));
        free_button.setFont(new java.awt.Font("Aharoni", 2, 14)); // NOI18N
        free_button.setText("FreeLancer");
        free_button.setOpaque(false);
        free_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                free_buttonActionPerformed(evt);
            }
        });
        chix_panel.add(free_button);
        free_button.setBounds(110, 166, 190, 40);

        prop_button.setBackground(new java.awt.Color(0, 147, 204));
        prop_button.setFont(new java.awt.Font("Aharoni", 2, 14)); // NOI18N
        prop_button.setText("Proprietaire de travail");
        prop_button.setOpaque(false);
        prop_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prop_buttonActionPerformed(evt);
            }
        });
        chix_panel.add(prop_button);
        prop_button.setBounds(110, 285, 190, 40);

        prop_insc_panel.setOpaque(false);
        prop_insc_panel.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Prenom :");
        prop_insc_panel.add(jLabel11);
        jLabel11.setBounds(12, 33, 70, 17);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nom :");
        prop_insc_panel.add(jLabel12);
        jLabel12.setBounds(12, 79, 40, 17);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Email :");
        prop_insc_panel.add(jLabel13);
        jLabel13.setBounds(12, 136, 50, 17);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Pays :");
        prop_insc_panel.add(jLabel14);
        jLabel14.setBounds(12, 190, 40, 17);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ville :");
        prop_insc_panel.add(jLabel15);
        jLabel15.setBounds(12, 239, 50, 17);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Login :");
        prop_insc_panel.add(jLabel16);
        jLabel16.setBounds(12, 293, 44, 17);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Mot de passe :");
        prop_insc_panel.add(jLabel17);
        jLabel17.setBounds(12, 339, 88, 17);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nom Entreprise :");
        prop_insc_panel.add(jLabel18);
        jLabel18.setBounds(12, 389, 105, 17);

        prenom_insc_prop.setOpaque(false);
        prop_insc_panel.add(prenom_insc_prop);
        prenom_insc_prop.setBounds(145, 30, 190, 30);

        nom_insc_prop.setOpaque(false);
        prop_insc_panel.add(nom_insc_prop);
        nom_insc_prop.setBounds(145, 66, 190, 30);

        email_insc_prop.setOpaque(false);
        prop_insc_panel.add(email_insc_prop);
        email_insc_prop.setBounds(145, 120, 190, 30);

        pays_insc_prop.setOpaque(false);
        pays_insc_prop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pays_insc_propActionPerformed(evt);
            }
        });
        prop_insc_panel.add(pays_insc_prop);
        pays_insc_prop.setBounds(145, 177, 190, 30);

        ville_insc_prop.setOpaque(false);
        prop_insc_panel.add(ville_insc_prop);
        ville_insc_prop.setBounds(145, 226, 190, 30);

        log_insc_prop.setOpaque(false);
        prop_insc_panel.add(log_insc_prop);
        log_insc_prop.setBounds(145, 280, 190, 30);

        entrep_insc_prop.setOpaque(false);
        entrep_insc_prop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrep_insc_propActionPerformed(evt);
            }
        });
        prop_insc_panel.add(entrep_insc_prop);
        entrep_insc_prop.setBounds(145, 376, 190, 30);

        pwd_insc_prop.setOpaque(false);
        pwd_insc_prop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd_insc_propActionPerformed(evt);
            }
        });
        prop_insc_panel.add(pwd_insc_prop);
        pwd_insc_prop.setBounds(145, 326, 190, 30);

        incrire_button_prop.setText("Inscrire");
        incrire_button_prop.setOpaque(false);
        incrire_button_prop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrire_button_propActionPerformed(evt);
            }
        });
        prop_insc_panel.add(incrire_button_prop);
        incrire_button_prop.setBounds(289, 472, 69, 23);

        premier_pas_panel.setOpaque(false);

        jLabel19.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 51));
        jLabel19.setText("Login :");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 51));
        jLabel20.setText("Mot de Passe :");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 51));
        jLabel21.setText("User_type :");

        log_text.setOpaque(false);

        pwd_text.setOpaque(false);

        type_text.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrateur", "Freelancer", "Propriétaire" }));
        type_text.setOpaque(false);
        type_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_textActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 147, 204));
        jButton1.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 51));
        jButton1.setText("Connexion");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout premier_pas_panelLayout = new javax.swing.GroupLayout(premier_pas_panel);
        premier_pas_panel.setLayout(premier_pas_panelLayout);
        premier_pas_panelLayout.setHorizontalGroup(
            premier_pas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(premier_pas_panelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(premier_pas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(premier_pas_panelLayout.createSequentialGroup()
                        .addGroup(premier_pas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(25, 25, 25)
                        .addGroup(premier_pas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(log_text, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type_text, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwd_text, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        premier_pas_panelLayout.setVerticalGroup(
            premier_pas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(premier_pas_panelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(premier_pas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(log_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(28, 28, 28)
                .addGroup(premier_pas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(pwd_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(premier_pas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(type_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        prop_insc_panel.add(premier_pas_panel);
        premier_pas_panel.setBounds(0, 0, 390, 510);

        chix_panel.add(prop_insc_panel);
        prop_insc_panel.setBounds(0, 0, 390, 510);

        free_insc_panel.add(chix_panel);
        chix_panel.setBounds(0, 0, 390, 510);

        deux_button_panel.add(free_insc_panel);
        free_insc_panel.setBounds(10, 0, 390, 510);

        body.add(deux_button_panel);
        deux_button_panel.setBounds(160, 0, 400, 510);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testtttttttttttt22/12121212.jpg"))); // NOI18N
        body.add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inscr_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscr_buttonActionPerformed

        deux_button_panel.setVisible(true);
        free_insc_panel.setVisible(false);
        chix_panel.setVisible(true);
        prop_insc_panel.setVisible(false);
        premier_pas_panel.setVisible(false);
        //************

        deux_button_panel.removeAll();
        deux_button_panel.repaint();
        deux_button_panel.revalidate();
        deux_button_panel.add(chix_panel);
        deux_button_panel.repaint();
        deux_button_panel.revalidate();
    }//GEN-LAST:event_inscr_buttonActionPerformed

    private void conn_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conn_buttonActionPerformed
        deux_button_panel.setVisible(true);
        free_insc_panel.setVisible(false);
        chix_panel.setVisible(false);
        prop_insc_panel.setVisible(false);
        premier_pas_panel.setVisible(true);

        //****
        deux_button_panel.removeAll();
        deux_button_panel.repaint();
        deux_button_panel.revalidate();
        deux_button_panel.add(premier_pas_panel);
        deux_button_panel.repaint();
        deux_button_panel.revalidate();
    }//GEN-LAST:event_conn_buttonActionPerformed

    private void inscrire_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscrire_buttonActionPerformed

        String prenom="";
        String nom="";
        String email="";
        String pays="";
        String ville="";
        String login="";
        String pwd="";

        prenom=prenom_text_free.getText();
        nom=nom_text_free.getText();
        email=email_text_free.getText();
        pays=pays_text_free.getText();
        ville=ville_text_free.getText();;
        login=log_text_free.getText();
        pwd=pwd_text_free.getText();
        boolean vasez=false;

        //***********************************test sur le Prenom**********************************
        if(!(prenom.isEmpty()))
        {   boolean exist=false;
            char[] prenom1;
            prenom1=prenom.toString().toCharArray();
            for(int i=0;((i<prenom.length())&&(exist==false));i++)
            {
                if((prenom1[i]!='0')||(prenom1[i]!='1')||(prenom1[i]!='2')||(prenom1[i]!='3')||(prenom1[i]!='4')||(prenom1[i]!='5')||(prenom1[i]!='6')||(prenom1[i]!='7')||(prenom1[i]!='8')||(prenom1[i]!='9'))
                {
                    exist=true;
                }
            }
            if(exist==false)
            {
                JOptionPane.showMessageDialog(null, "Prenom Incoorecte");
            }

            //********************************Test Pour le Nom****************************************
            if(!(nom.isEmpty()))
            {
                exist=true;
                char[] nom1;
                nom1=nom.toString().toCharArray();
                for(int i=0;((i<nom.length())&&(exist==false));i++)
                {
                    if((nom1[i]!='0')||(nom1[i]!='1')||(nom1[i]!='2')||(nom1[i]!='3')||(nom1[i]!='4')||(nom1[i]!='5')||(nom1[i]!='6')||(nom1[i]!='7')||(nom1[i]!='8')||(nom1[i]!='9'))
                    {
                        exist=false;
                    }
                }
                if(exist==false)
                {
                    JOptionPane.showMessageDialog(null, "Nom Incoorecte");
                }
                //*******************************************test de email***************************************
                if(!(email.isEmpty()))
                {
                    exist=true;
                    boolean go=true;
                    int nb=0;
                    char[] email1;
                    email1=email.toString().toCharArray();
                    int length=email.length()-1;
                    if((email1[0]!='.')&&(email1[0]!='@'))
                    {
                        go=true;

                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Attention: Email doit etre sous la Forme 'xxxx@xx.xx 2'");
                        go=false;
                    }
                    if(go)
                    {
                        for(int i=1;(i<(email.length())&&(exist));i++)
                        {
                            if(email1[i]!='@')
                            {
                                exist=true;

                            }
                            else
                            {
                                exist=false;
                                nb=i;
                            }

                        }
                        if(exist==false)
                        {
                            exist=true;
                            for(int i=(nb+1);((i<email.length())&&(exist));i++)
                            {

                                if(email1[i]!='.')
                                {
                                    exist=true;
                                }
                                else if(i==length)
                                {
                                    if((email1[i]!='.')&&(email1[i]!='@'))
                                    {
                                        exist=true;

                                    }
                                }
                                else
                                exist=false;
                            }
                            if(exist)
                            JOptionPane.showMessageDialog(null, "Attention: Email doit etre sous la Forme 'xxxx@xx.xx 3'");
                        }
                        else
                        JOptionPane.showMessageDialog(null, "Attention: Email doit etre sous la Forme 'xxxx@xx.xx 4'");
                    }

                }
                else

                JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir l'email");
                //**************test Pays***********
                if(!(pays.isEmpty()))
                {    exist=false;
                    char[] pays1;
                    pays1=pays.toString().toCharArray();
                    for(int i=0;((i<pays.length())&&(exist==false));i++)
                    {
                        if((pays1[i]!='0')||(pays1[i]!='1')||(pays1[i]!='2')||(pays1[i]!='3')||(pays1[i]!='4')||(pays1[i]!='5')||(pays1[i]!='6')||(pays1[i]!='7')||(pays1[i]!='8')||(pays1[i]!='9'))
                        {
                            exist=true;
                        }
                    }
                    if(exist==false)
                    {
                        JOptionPane.showMessageDialog(null, "Pays Incoorecte");
                    }
                    //*****************test ville******************
                    if(!(ville.isEmpty()))
                    {    exist=false;
                        char[] ville1;
                        ville1=ville.toString().toCharArray();
                        for(int i=0;((i<ville.length())&&(exist==false));i++)
                        {
                            if((ville1[i]!='0')||(ville1[i]!='1')||(ville1[i]!='2')||(ville1[i]!='3')||(ville1[i]!='4')||(ville1[i]!='5')||(ville1[i]!='6')||(ville1[i]!='7')||(ville1[i]!='8')||(ville1[i]!='9'))
                            {
                                exist=true;
                            }
                        }
                        if(exist==false)
                        {
                            JOptionPane.showMessageDialog(null, "Ville Incoorecte");
                        }

                        //***********tester Login****************
                        if(!(login.isEmpty()))
                        {
                            if(!(pwd.isEmpty()))
                            {
                                vasez=true;
                            }

                            else
                            JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir Mot de passe ");
                        }

                        else
                        JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir Login ");
                    }
                    else
                    JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir le ville ");
                }
                else
                JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir le pays ");
            }
            else
            JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir le Nom ");
        }
        else
        JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir le Prenom ");

        //*****************Ajout de Freelancer*///////////////////////////////////////////////
        if(vasez)
        {
            String ch="actif";
            int x=0;
            freelancer free=new freelancer(x,prenom, nom, email, pays, ville, login, pwd,ch);

            freelancerdao freedao;
            try {
               IFreelancer  ifreedao = freelancerdao.getInstance();
                ifreedao.createFreelancer(free);
                JOptionPane.showMessageDialog(null, "Insertion Reuissite -__-");
            } catch (SQLException ex) {
                Logger.getLogger(premiere_page.class.getName()).log(Level.SEVERE, null, ex);
            }

            //***********************

        }
    }//GEN-LAST:event_inscrire_buttonActionPerformed

    private void free_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_free_buttonActionPerformed

        deux_button_panel.setVisible(true);
        free_insc_panel.setVisible(true);
        chix_panel.setVisible(false);
        prop_insc_panel.setVisible(false);
        premier_pas_panel.setVisible(false);
        //************

        deux_button_panel.removeAll();
        deux_button_panel.repaint();
        deux_button_panel.revalidate();
        deux_button_panel.add(free_insc_panel);
        deux_button_panel.repaint();
        deux_button_panel.revalidate();
    }//GEN-LAST:event_free_buttonActionPerformed

    private void prop_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prop_buttonActionPerformed

        deux_button_panel.setVisible(true);
        free_insc_panel.setVisible(false);
        chix_panel.setVisible(false);
        prop_insc_panel.setVisible(true);
        premier_pas_panel.setVisible(false);
        //************

        deux_button_panel.removeAll();
        deux_button_panel.repaint();
        deux_button_panel.revalidate();
        deux_button_panel.add(prop_insc_panel);
        deux_button_panel.repaint();
        deux_button_panel.revalidate();
    }//GEN-LAST:event_prop_buttonActionPerformed

    private void pays_insc_propActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pays_insc_propActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pays_insc_propActionPerformed

    private void entrep_insc_propActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrep_insc_propActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrep_insc_propActionPerformed

    private void incrire_button_propActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrire_button_propActionPerformed

        String prenom="";
        String nom="";
        String email="";
        String pays="";
        String ville="";
        String login="";
        String pwd="";
        String entrep="";
        String statut="actif";
        prenom=prenom_insc_prop.getText();
        nom=nom_insc_prop.getText();
        email=email_insc_prop.getText();
        pays=pays_insc_prop.getText();
        ville=ville_insc_prop.getText();;
        login=log_insc_prop.getText();
        pwd=pwd_insc_prop.getText();
        entrep=entrep_insc_prop.getText();
        boolean vasez=false;

        //***********************************test sur le Prenom**********************************
        if(!(prenom.isEmpty()))
        {   boolean exist=false;
            char[] prenom1;
            prenom1=prenom.toString().toCharArray();
            for(int i=0;((i<prenom.length())&&(exist==false));i++)
            {
                if((prenom1[i]!='0')||(prenom1[i]!='1')||(prenom1[i]!='2')||(prenom1[i]!='3')||(prenom1[i]!='4')||(prenom1[i]!='5')||(prenom1[i]!='6')||(prenom1[i]!='7')||(prenom1[i]!='8')||(prenom1[i]!='9'))
                {
                    exist=true;
                }
            }
            if(exist==false)
            {
                JOptionPane.showMessageDialog(null, "Prenom Incoorecte");
            }

            //********************************Test Pour le Nom****************************************
            if(!(nom.isEmpty()))
            {
                exist=true;
                char[] nom1;
                nom1=nom.toString().toCharArray();
                for(int i=0;((i<nom.length())&&(exist==false));i++)
                {
                    if((nom1[i]!='0')||(nom1[i]!='1')||(nom1[i]!='2')||(nom1[i]!='3')||(nom1[i]!='4')||(nom1[i]!='5')||(nom1[i]!='6')||(nom1[i]!='7')||(nom1[i]!='8')||(nom1[i]!='9'))
                    {
                        exist=false;
                    }
                }
                if(exist==false)
                {
                    JOptionPane.showMessageDialog(null, "Nom Incoorecte");
                }
                //*******************************************test de email***************************************
                if(!(email.isEmpty()))
                {
                    exist=true;
                    boolean go=true;
                    int nb=0;
                    char[] email1;
                    email1=email.toString().toCharArray();
                    int length=email.length()-1;
                    if((email1[0]!='.')&&(email1[0]!='@'))
                    {
                        go=true;

                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Attention: Email doit etre sous la Forme 'xxxx@xx.xx 2'");
                        go=false;
                    }
                    if(go)
                    {
                        for(int i=1;(i<(email.length())&&(exist));i++)
                        {
                            if(email1[i]!='@')
                            {
                                exist=true;

                            }
                            else
                            {
                                exist=false;
                                nb=i;
                            }

                        }
                        if(exist==false)
                        {
                            exist=true;
                            for(int i=(nb+1);((i<email.length())&&(exist));i++)
                            {

                                if(email1[i]!='.')
                                {
                                    exist=true;
                                }
                                else if(i==length)
                                {
                                    if((email1[i]!='.')&&(email1[i]!='@'))
                                    {
                                        exist=true;

                                    }
                                }
                                else
                                exist=false;
                            }
                            if(exist)
                            JOptionPane.showMessageDialog(null, "Attention: Email doit etre sous la Forme 'xxxx@xx.xx 3'");
                        }
                        else
                        JOptionPane.showMessageDialog(null, "Attention: Email doit etre sous la Forme 'xxxx@xx.xx 4'");
                    }

                }
                else

                JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir l'email");
                //**************test Pays***********
                if(!(pays.isEmpty()))
                {    exist=false;
                    char[] pays1;
                    pays1=pays.toString().toCharArray();
                    for(int i=0;((i<pays.length())&&(exist==false));i++)
                    {
                        if((pays1[i]!='0')||(pays1[i]!='1')||(pays1[i]!='2')||(pays1[i]!='3')||(pays1[i]!='4')||(pays1[i]!='5')||(pays1[i]!='6')||(pays1[i]!='7')||(pays1[i]!='8')||(pays1[i]!='9'))
                        {
                            exist=true;
                        }
                    }
                    if(exist==false)
                    {
                        JOptionPane.showMessageDialog(null, "Pays Incoorecte");
                    }
                    //*****************test ville******************
                    if(!(ville.isEmpty()))
                    {    exist=false;
                        char[] ville1;
                        ville1=ville.toString().toCharArray();
                        for(int i=0;((i<ville.length())&&(exist==false));i++)
                        {
                            if((ville1[i]!='0')||(ville1[i]!='1')||(ville1[i]!='2')||(ville1[i]!='3')||(ville1[i]!='4')||(ville1[i]!='5')||(ville1[i]!='6')||(ville1[i]!='7')||(ville1[i]!='8')||(ville1[i]!='9'))
                            {
                                exist=true;
                            }
                        }
                        if(exist==false)
                        {
                            JOptionPane.showMessageDialog(null, "Ville Incoorecte");
                        }

                        //***********tester Login****************
                        if(!(login.isEmpty()))
                        {
                            if(!(pwd.isEmpty()))
                            {
                                if(!(entrep.isEmpty()))
                                {

                                    vasez=true;
                                }

                                else
                                JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir Nom De Votre Entreprise ");
                            }

                            else
                            JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir Mot de passe ");
                        }

                        else
                        JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir Login ");
                    }
                    else
                    JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir le ville ");
                }
                else
                JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir le pays ");
            }
            else
            JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir le Nom ");
        }
        else
        JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir le Prenom ");
        //*****************Ajout de Freelancer*///////////////////////////////////////////////
        if(vasez)
        {
            int x=0;
            proprietaire free=new proprietaire(x,prenom, nom, email, pays, ville, login, pwd, entrep, statut);

            proprietairedao freedao =new proprietairedao();
            freedao.createProprietaire(free);
            JOptionPane.showMessageDialog(null, "Insertion Reuissite -__-");

        }
    }//GEN-LAST:event_incrire_button_propActionPerformed

    private void type_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type_textActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String login="";
        String pwd="";
        login=log_text.getText();
        pwd=pwd_text.getText();
        String user_type="";
        if(type_text.getSelectedIndex()==0)
        user_type="administrateur";
        else if (type_text.getSelectedIndex()==1)
        user_type="freelancer";
        else
        user_type="proprietaire";
        if(!(login.isEmpty()))
        {
            if(!(pwd.isEmpty()))
            {

            }
            else
            JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir Password");
        }
        else
        JOptionPane.showMessageDialog(null, "Attetion : Faut Saisir Login ");
        //******************Teste de Administrateur************
        if(user_type.equals("administrateur"))
        {
            Administrateurdao adminn= new Administrateurdao();
            administrateur admin=new administrateur();
            admin=adminn.findById(1);
            if((admin.getLogin().equals(login))&&(admin.getPwd().equals(pwd)))
            {
                    administrateur_interface page=new administrateur_interface();
                    page.setVisible(true);
            }
            else
            JOptionPane.showMessageDialog(null, "Attetion : Login ou mot de passe Erronée ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pwd_insc_propActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd_insc_propActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwd_insc_propActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(premiere_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(premiere_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(premiere_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(premiere_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new premiere_page().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel body1;
    private javax.swing.JPanel chix_panel;
    private javax.swing.JButton conn_button;
    private javax.swing.JPanel deux_button_panel;
    private javax.swing.JTextField email_insc_prop;
    private javax.swing.JTextField email_text_free;
    private javax.swing.JTextField entrep_insc_prop;
    private javax.swing.JButton free_button;
    private javax.swing.JPanel free_insc_panel;
    private javax.swing.JButton incrire_button_prop;
    private javax.swing.JButton inscr_button;
    private javax.swing.JButton inscrire_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField log_insc_prop;
    private javax.swing.JTextField log_text;
    private javax.swing.JTextField log_text_free;
    private javax.swing.JTextField nom_insc_prop;
    private javax.swing.JTextField nom_text_free;
    private javax.swing.JTextField pays_insc_prop;
    private javax.swing.JTextField pays_text_free;
    private javax.swing.JPanel premier_pas_panel;
    private javax.swing.JTextField prenom_insc_prop;
    private javax.swing.JTextField prenom_text_free;
    private javax.swing.JButton prop_button;
    private javax.swing.JPanel prop_insc_panel;
    private javax.swing.JPasswordField pwd_insc_prop;
    private javax.swing.JTextField pwd_text;
    private javax.swing.JPasswordField pwd_text_free;
    private javax.swing.JComboBox type_text;
    private javax.swing.JTextField ville_insc_prop;
    private javax.swing.JTextField ville_text_free;
    // End of variables declaration//GEN-END:variables
}
