/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.gui;

import edu.esprit.dao.classes.CategorieDAO;
import edu.esprit.dao.classes.MailDAO;
import edu.esprit.dao.classes.PropositionDAO;
import edu.esprit.dao.classes.freelancerdao;
import edu.esprit.dao.classes.proprietairedao;
import edu.esprit.dao.interfaces.ICategorieDAO;
import edu.esprit.dao.interfaces.IFreelancer;
import edu.esprit.dao.interfaces.IProposition;
import edu.esprit.dao.interfaces.ImailDAO;
import edu.esprit.dao.interfaces.Iproprietairedao;
import edu.esprit.entities.Categorie;
import edu.esprit.entities.Mail;
import edu.esprit.entities.Proposition;
import edu.esprit.entities.freelancer;
import edu.esprit.entities.proprietaire;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.JFileChooser;
import java.text.DateFormat;
import sun.misc.Cleaner;

/**
 *
 * @author khalil
 */
public class administrateur_interface extends javax.swing.JFrame {

    /**
     * Creates new form administrateur_interface
     */
    URL url;
    
    public administrateur_interface() {
        initComponents();
        panel_verrouil.setVisible(false);
        free_gestion.setVisible(false);
        panel_prop.setVisible(false);
        prop_verrou.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel36 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nom_cat = new javax.swing.JTextField();
        type_cat = new javax.swing.JTextField();
        ajouter_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        modifier_button = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        idcat = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        general_panel = new javax.swing.JPanel();
        free_gestion = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        supprime_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        oui_button = new javax.swing.JButton();
        panel_verrouil = new javax.swing.JPanel();
        ver_button = new javax.swing.JButton();
        verr_button = new javax.swing.JButton();
        retour_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        prenom_text = new javax.swing.JTextField();
        nom_text = new javax.swing.JTextField();
        email_text = new javax.swing.JTextField();
        pays_text = new javax.swing.JTextField();
        ville_text = new javax.swing.JTextField();
        login_text = new javax.swing.JTextField();
        pwd_text = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        statut_text = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        id_text = new javax.swing.JTextField();
        panel_trois_boutton = new javax.swing.JPanel();
        free_button = new javax.swing.JButton();
        prop_button = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        panel_prop = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table3_1 = new javax.swing.JTable();
        supprime_prop = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        prop_verrou = new javax.swing.JPanel();
        dev_prop = new javax.swing.JButton();
        verr_prop = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        id_text_prop = new javax.swing.JTextField();
        prenom_text_prop = new javax.swing.JTextField();
        nom_text_prop = new javax.swing.JTextField();
        email_text_prop = new javax.swing.JTextField();
        pays_text_prop = new javax.swing.JTextField();
        ville_text_prop = new javax.swing.JTextField();
        login_text_prop = new javax.swing.JTextField();
        pwd_text_prop = new javax.swing.JTextField();
        entrp_text_prop = new javax.swing.JTextField();
        statut_text_prop = new javax.swing.JTextField();
        retour_prop_button = new javax.swing.JButton();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        email_admin = new javax.swing.JTextField();
        pwd_admin = new javax.swing.JTextField();
        email_recep = new javax.swing.JTextField();
        sujet = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        msg = new javax.swing.JTextArea();
        envoie_button = new javax.swing.JButton();
        chos_fichier_button = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        piece_jointe = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        stat = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        prop1 = new javax.swing.JTextField();
        prop2 = new javax.swing.JTextField();
        prop3 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/image/Freelancing.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        table1.setModel(new ListCategories());
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jScrollPane1.setBounds(0, 10, 452, 150);
        jDesktopPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Nom :");
        jLabel2.setBounds(530, 130, 35, 16);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Type :");
        jLabel3.setBounds(530, 180, 37, 16);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nom_cat.setBounds(590, 130, 110, 22);
        jDesktopPane1.add(nom_cat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        type_cat.setBounds(590, 180, 110, 22);
        jDesktopPane1.add(type_cat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ajouter_button.setText("Ajouter");
        ajouter_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter_buttonActionPerformed(evt);
            }
        });
        ajouter_button.setBounds(140, 370, 75, 25);
        jDesktopPane1.add(ajouter_button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(330, 370, 93, 25);
        jDesktopPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        modifier_button.setText("Modifier");
        modifier_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifier_buttonActionPerformed(evt);
            }
        });
        modifier_button.setBounds(530, 370, 79, 25);
        jDesktopPane1.add(modifier_button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel30.setText("Id:");
        jLabel30.setBounds(530, 90, 48, 16);
        jDesktopPane1.add(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        idcat.setBounds(590, 90, 110, 22);
        jDesktopPane1.add(idcat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/image/Freelancing.jpg"))); // NOI18N
        jLabel35.setBounds(0, 0, 760, 480);
        jDesktopPane1.add(jLabel35, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane2.addTab("Gestion Categories", jDesktopPane1);

        jDesktopPane3.setBackground(new java.awt.Color(255, 255, 255));

        general_panel.setLayout(null);

        free_gestion.setLayout(null);

        table3.setModel(new ListUsers());
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table3);

        free_gestion.add(jScrollPane3);
        jScrollPane3.setBounds(12, 65, 506, 160);

        supprime_button.setText("Supprimer");
        supprime_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprime_buttonActionPerformed(evt);
            }
        });
        free_gestion.add(supprime_button);
        supprime_button.setBounds(30, 280, 93, 25);

        jLabel1.setText("Verrouiller/Deverrouiller ?");
        free_gestion.add(jLabel1);
        jLabel1.setBounds(190, 240, 148, 16);

        oui_button.setText("Oui");
        oui_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oui_buttonActionPerformed(evt);
            }
        });
        free_gestion.add(oui_button);
        oui_button.setBounds(240, 280, 51, 25);

        panel_verrouil.setLayout(null);

        ver_button.setText("Deverrouiller");
        ver_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_buttonActionPerformed(evt);
            }
        });
        panel_verrouil.add(ver_button);
        ver_button.setBounds(51, 32, 105, 25);

        verr_button.setText("Verrouiller");
        verr_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verr_buttonActionPerformed(evt);
            }
        });
        panel_verrouil.add(verr_button);
        verr_button.setBounds(51, 96, 105, 25);

        free_gestion.add(panel_verrouil);
        panel_verrouil.setBounds(160, 320, 190, 150);

        retour_button.setText("Retour");
        retour_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour_buttonActionPerformed(evt);
            }
        });
        free_gestion.add(retour_button);
        retour_button.setBounds(700, 450, 71, 25);

        jLabel4.setText("Prenom :");
        free_gestion.add(jLabel4);
        jLabel4.setBounds(550, 30, 60, 16);

        jLabel5.setText("Nom :");
        free_gestion.add(jLabel5);
        jLabel5.setBounds(550, 70, 41, 16);

        jLabel6.setText("Email :");
        free_gestion.add(jLabel6);
        jLabel6.setBounds(550, 110, 41, 16);

        jLabel7.setText("Password :");
        free_gestion.add(jLabel7);
        jLabel7.setBounds(550, 280, 70, 16);

        jLabel8.setText("Pays :");
        free_gestion.add(jLabel8);
        jLabel8.setBounds(550, 160, 41, 16);

        jLabel9.setText("Ville :");
        free_gestion.add(jLabel9);
        jLabel9.setBounds(550, 200, 33, 16);

        jLabel10.setText("Login :");
        free_gestion.add(jLabel10);
        jLabel10.setBounds(550, 240, 41, 16);
        free_gestion.add(prenom_text);
        prenom_text.setBounds(650, 30, 100, 22);
        free_gestion.add(nom_text);
        nom_text.setBounds(650, 70, 100, 22);
        free_gestion.add(email_text);
        email_text.setBounds(650, 110, 100, 22);
        free_gestion.add(pays_text);
        pays_text.setBounds(650, 160, 100, 22);
        free_gestion.add(ville_text);
        ville_text.setBounds(650, 200, 100, 22);
        free_gestion.add(login_text);
        login_text.setBounds(650, 240, 100, 22);
        free_gestion.add(pwd_text);
        pwd_text.setBounds(650, 280, 100, 22);

        jLabel11.setText("Statut :");
        free_gestion.add(jLabel11);
        jLabel11.setBounds(550, 320, 43, 16);
        free_gestion.add(statut_text);
        statut_text.setBounds(650, 320, 100, 22);

        jLabel12.setText("ID :");
        free_gestion.add(jLabel12);
        jLabel12.setBounds(550, 0, 21, 16);
        free_gestion.add(id_text);
        id_text.setBounds(650, 0, 100, 22);

        general_panel.add(free_gestion);
        free_gestion.setBounds(0, 0, 780, 480);

        panel_trois_boutton.setLayout(null);

        free_button.setText("Freelancer");
        free_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                free_buttonActionPerformed(evt);
            }
        });
        panel_trois_boutton.add(free_button);
        free_button.setBounds(129, 41, 149, 38);

        prop_button.setText("Propriétaire");
        prop_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prop_buttonActionPerformed(evt);
            }
        });
        panel_trois_boutton.add(prop_button);
        prop_button.setBounds(129, 130, 149, 40);

        jButton10.setText("Sous Administrateur");
        panel_trois_boutton.add(jButton10);
        jButton10.setBounds(129, 189, 149, 41);

        general_panel.add(panel_trois_boutton);
        panel_trois_boutton.setBounds(220, 120, 400, 270);

        panel_prop.setLayout(null);

        table3_1.setModel(new Listprop());
        table3_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3_1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table3_1);

        panel_prop.add(jScrollPane2);
        jScrollPane2.setBounds(20, 68, 452, 120);

        supprime_prop.setText("Supprimer");
        supprime_prop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprime_propActionPerformed(evt);
            }
        });
        panel_prop.add(supprime_prop);
        supprime_prop.setBounds(20, 233, 93, 25);

        jLabel13.setText("Deverrouiller/Verouiller ?");
        panel_prop.add(jLabel13);
        jLabel13.setBounds(209, 233, 143, 16);

        jButton5.setText("Oui");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel_prop.add(jButton5);
        jButton5.setBounds(255, 276, 51, 25);

        prop_verrou.setLayout(null);

        dev_prop.setText("Deverrouiller");
        dev_prop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dev_propActionPerformed(evt);
            }
        });
        prop_verrou.add(dev_prop);
        dev_prop.setBounds(20, 30, 105, 25);

        verr_prop.setText("Verrouiller");
        verr_prop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verr_propActionPerformed(evt);
            }
        });
        prop_verrou.add(verr_prop);
        verr_prop.setBounds(20, 90, 105, 25);

        panel_prop.add(prop_verrou);
        prop_verrou.setBounds(210, 310, 150, 150);

        jLabel14.setText("Id :");
        panel_prop.add(jLabel14);
        jLabel14.setBounds(530, 30, 20, 16);

        jLabel15.setText("Prenom :");
        panel_prop.add(jLabel15);
        jLabel15.setBounds(530, 80, 53, 16);

        jLabel16.setText("Nom :");
        panel_prop.add(jLabel16);
        jLabel16.setBounds(530, 120, 35, 16);

        jLabel17.setText("Email :");
        panel_prop.add(jLabel17);
        jLabel17.setBounds(530, 180, 40, 16);

        jLabel18.setText("Pays :");
        panel_prop.add(jLabel18);
        jLabel18.setBounds(530, 230, 35, 16);

        jLabel19.setText("Ville :");
        panel_prop.add(jLabel19);
        jLabel19.setBounds(530, 280, 33, 16);

        jLabel20.setText("Login :");
        panel_prop.add(jLabel20);
        jLabel20.setBounds(530, 330, 39, 16);

        jLabel21.setText("Password :");
        panel_prop.add(jLabel21);
        jLabel21.setBounds(530, 380, 70, 16);

        jLabel22.setText("Nom Entreprise :");
        panel_prop.add(jLabel22);
        jLabel22.setBounds(520, 410, 100, 16);

        jLabel23.setText("Statut :");
        panel_prop.add(jLabel23);
        jLabel23.setBounds(530, 450, 43, 16);
        panel_prop.add(id_text_prop);
        id_text_prop.setBounds(630, 20, 120, 22);
        panel_prop.add(prenom_text_prop);
        prenom_text_prop.setBounds(630, 70, 120, 22);
        panel_prop.add(nom_text_prop);
        nom_text_prop.setBounds(630, 120, 120, 22);
        panel_prop.add(email_text_prop);
        email_text_prop.setBounds(630, 170, 120, 22);
        panel_prop.add(pays_text_prop);
        pays_text_prop.setBounds(630, 220, 120, 22);
        panel_prop.add(ville_text_prop);
        ville_text_prop.setBounds(630, 270, 120, 22);
        panel_prop.add(login_text_prop);
        login_text_prop.setBounds(630, 320, 120, 22);
        panel_prop.add(pwd_text_prop);
        pwd_text_prop.setBounds(630, 370, 120, 22);
        panel_prop.add(entrp_text_prop);
        entrp_text_prop.setBounds(630, 410, 120, 22);
        panel_prop.add(statut_text_prop);
        statut_text_prop.setBounds(630, 440, 120, 22);

        retour_prop_button.setText("Retour");
        retour_prop_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour_prop_buttonActionPerformed(evt);
            }
        });
        panel_prop.add(retour_prop_button);
        retour_prop_button.setBounds(10, 450, 71, 25);

        general_panel.add(panel_prop);
        panel_prop.setBounds(0, 0, 780, 480);

        general_panel.setBounds(0, 0, 780, 480);
        jDesktopPane3.add(general_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane2.addTab("Gestion des Comptes utilisateurs ", jDesktopPane3);

        jDesktopPane4.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.addTab("Verifier statistique", jDesktopPane4);

        jDesktopPane5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setText("Email Administrateur :");
        jLabel24.setBounds(20, 20, 150, 16);
        jDesktopPane5.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel25.setText("Mot de passe :");
        jLabel25.setBounds(20, 70, 130, 16);
        jDesktopPane5.add(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel26.setText("Email Recepteur :");
        jLabel26.setBounds(20, 110, 130, 16);
        jDesktopPane5.add(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel27.setText("Sujet :");
        jLabel27.setBounds(20, 150, 130, 16);
        jDesktopPane5.add(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel28.setText("Message :");
        jLabel28.setBounds(20, 190, 110, 16);
        jDesktopPane5.add(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        email_admin.setBounds(260, 20, 200, 22);
        jDesktopPane5.add(email_admin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pwd_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd_adminActionPerformed(evt);
            }
        });
        pwd_admin.setBounds(260, 70, 200, 22);
        jDesktopPane5.add(pwd_admin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        email_recep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_recepActionPerformed(evt);
            }
        });
        email_recep.setBounds(260, 110, 200, 22);
        jDesktopPane5.add(email_recep, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sujet.setBounds(260, 150, 200, 22);
        jDesktopPane5.add(sujet, javax.swing.JLayeredPane.DEFAULT_LAYER);

        msg.setColumns(20);
        msg.setRows(5);
        jScrollPane5.setViewportView(msg);

        jScrollPane5.setBounds(260, 200, 210, 150);
        jDesktopPane5.add(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        envoie_button.setText("Envoyer");
        envoie_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envoie_buttonActionPerformed(evt);
            }
        });
        envoie_button.setBounds(650, 420, 77, 25);
        jDesktopPane5.add(envoie_button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        chos_fichier_button.setText("Selectionner Fichier");
        chos_fichier_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chos_fichier_buttonActionPerformed(evt);
            }
        });
        chos_fichier_button.setBounds(440, 420, 150, 25);
        jDesktopPane5.add(chos_fichier_button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel29.setText("URL piéce Jointe :");
        jLabel29.setBounds(20, 390, 110, 16);
        jDesktopPane5.add(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        piece_jointe.setBounds(260, 380, 210, 30);
        jDesktopPane5.add(piece_jointe, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/image/Freelancing.jpg"))); // NOI18N
        jLabel37.setBounds(0, 0, 760, 480);
        jDesktopPane5.add(jLabel37, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane2.addTab("Envoyer Email", jDesktopPane5);

        jDesktopPane6.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane6.setOpaque(false);

        stat.setOpaque(false);
        stat.setBounds(180, 370, 120, 30);
        jDesktopPane6.add(stat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel31.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Statut:");
        jLabel31.setBounds(70, 380, 60, 30);
        jDesktopPane6.add(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton9.setBackground(new java.awt.Color(0, 147, 204));
        jButton9.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Valider");
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jButton9.setBounds(610, 430, 90, 30);
        jDesktopPane6.add(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel32.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("id:");
        jLabel32.setBounds(70, 250, 18, 19);
        jDesktopPane6.add(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel33.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("titre:");
        jLabel33.setBounds(70, 290, 35, 19);
        jDesktopPane6.add(jLabel33, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel34.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("description:");
        jLabel34.setBounds(70, 330, 90, 20);
        jDesktopPane6.add(jLabel34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prop1.setOpaque(false);
        prop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prop1ActionPerformed(evt);
            }
        });
        prop1.setBounds(180, 240, 120, 30);
        jDesktopPane6.add(prop1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prop2.setOpaque(false);
        prop2.setBounds(180, 280, 120, 30);
        jDesktopPane6.add(prop2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prop3.setOpaque(false);
        prop3.setBounds(180, 320, 120, 30);
        jDesktopPane6.add(prop3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane6.setOpaque(false);

        table2.setModel(new ListProposition());
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(table2);

        jScrollPane6.setBounds(50, 20, 440, 120);
        jDesktopPane6.add(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLabel41.setBounds(0, -20, 0, 530);
        jDesktopPane6.add(jLabel41, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLabel42.setBounds(0, -20, 770, 510);
        jDesktopPane6.add(jLabel42, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/image/Freelancing.jpg"))); // NOI18N
        jLabel38.setBounds(0, 0, 760, 480);
        jDesktopPane6.add(jLabel38, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane2.addTab("Gestion Offres d'emplois", jDesktopPane6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ajouter_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter_buttonActionPerformed
       Categorie cat = new Categorie();
        int x;
        x = Integer.parseInt(idcat.getText());
        cat.setNom(nom_cat.getText());
        cat.setType(type_cat.getText());

        ICategorieDAO catdao = new CategorieDAO();
        catdao.save(cat);
        JOptionPane.showMessageDialog(null, "Insertion Reuissite -__-");
        table1.setModel(new ListCategories());
                   
        
    }//GEN-LAST:event_ajouter_buttonActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        
        int row = table1.getSelectedRow();
         idcat.setText(table1.getModel().getValueAt(row, 0).toString());
        nom_cat.setText(table1.getModel().getValueAt(row, 1).toString());   
        type_cat.setText(table1.getModel().getValueAt(row, 2).toString());
                
         
    }//GEN-LAST:event_table1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          ICategorieDAO cat_dao = new CategorieDAO();
        int x;
        x = Integer.parseInt(idcat.getText());
        String type = type_cat.getText();
        String nom = nom_cat.getText();
        Categorie categ = new Categorie(x, nom, type);
        cat_dao.delete(categ);
        table1.setModel(new ListCategories());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void modifier_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifier_buttonActionPerformed
      String nom = nom_cat.getText();
        String type = type_cat.getText();
        int x;
        x = Integer.parseInt(idcat.getText());

        Categorie cat = new Categorie(x, nom, type);


        ICategorieDAO catdao = new CategorieDAO();

        catdao.update(cat);

        table1.setModel(new ListCategories());
    }//GEN-LAST:event_modifier_buttonActionPerformed

    private void oui_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oui_buttonActionPerformed
        general_panel.setVisible(true);
        panel_trois_boutton.setVisible(false);
        panel_verrouil.setVisible(true);
    }//GEN-LAST:event_oui_buttonActionPerformed

    private void retour_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour_buttonActionPerformed
        general_panel.setVisible(true);
        panel_trois_boutton.setVisible(true);
        panel_verrouil.setVisible(false);
        panel_verrouil.setVisible(false);
        general_panel.removeAll();
        general_panel.repaint();
        general_panel.revalidate();
        general_panel.add(panel_trois_boutton);
        general_panel.repaint();
        general_panel.revalidate();
    }//GEN-LAST:event_retour_buttonActionPerformed

    private void supprime_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprime_buttonActionPerformed
       
        IFreelancer freedao=new freelancerdao();
        String id=id_text.getText();
        String prenom=prenom_text.getText();
        String nom=nom_text.getText();
        String email=email_text.getText();
        String pays=pays_text.getText();
        String ville=ville_text.getText();
        String login=login_text.getText();
        String pwd=pwd_text.getText();
        String statut=statut_text.getText();
        freelancer free = new freelancer();
        int idr=Integer.parseInt(id);
        free.setId(idr);
        free.setPrenom(prenom);
        free.setNom(nom);
        free.setEmail(email);
        free.setPays(pays);
        free.setVille(ville);
        free.setLogin(login);
        free.setPwd(pwd);
        free.setStatus(statut);
        
        freedao.delete(free);
        table3.setModel(new ListUsers());
    }//GEN-LAST:event_supprime_buttonActionPerformed

    private void table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseClicked
        int row = table3.getSelectedRow();
        id_text.setText(table3.getModel().getValueAt(row, 0).toString());
        prenom_text.setText(table3.getModel().getValueAt(row, 1).toString());   
        nom_text.setText(table3.getModel().getValueAt(row, 2).toString());
        email_text.setText(table3.getModel().getValueAt(row, 3).toString());   
        pays_text.setText(table3.getModel().getValueAt(row, 4).toString());
        ville_text.setText(table3.getModel().getValueAt(row, 5).toString());   
        login_text.setText(table3.getModel().getValueAt(row, 6).toString());
        pwd_text.setText(table3.getModel().getValueAt(row, 7).toString());
        statut_text.setText(table3.getModel().getValueAt(row, 8).toString());
    }//GEN-LAST:event_table3MouseClicked

    private void ver_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_buttonActionPerformed
            IFreelancer freedao=new freelancerdao();
        String id=id_text.getText();
        String prenom=prenom_text.getText();
        String nom=nom_text.getText();
        String email=email_text.getText();
        String pays=pays_text.getText();
        String ville=ville_text.getText();
        String login=login_text.getText();
        String pwd=pwd_text.getText();
        String statut=statut_text.getText();
        freelancer free = new freelancer();
        int idr=Integer.parseInt(id);
        free.setId(idr);
        free.setPrenom(prenom);
        free.setNom(nom);
        free.setEmail(email);
        free.setPays(pays);
        free.setVille(ville);
        free.setLogin(login);
        free.setPwd(pwd);
        free.setStatus(statut);
        
        freedao.update_actif(free);
        table3.setModel(new ListUsers());
    }//GEN-LAST:event_ver_buttonActionPerformed

    private void verr_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verr_buttonActionPerformed
         IFreelancer freedao=new freelancerdao();
        String id=id_text.getText();
        String prenom=prenom_text.getText();
        String nom=nom_text.getText();
        String email=email_text.getText();
        String pays=pays_text.getText();
        String ville=ville_text.getText();
        String login=login_text.getText();
        String pwd=pwd_text.getText();
        String statut=statut_text.getText();
        freelancer free = new freelancer();
        int idr=Integer.parseInt(id);
        free.setId(idr);
        free.setPrenom(prenom);
        free.setNom(nom);
        free.setEmail(email);
        free.setPays(pays);
        free.setVille(ville);
        free.setLogin(login);
        free.setPwd(pwd);
        free.setStatus(statut);
        
        freedao.update_nonactif(free);
        table3.setModel(new ListUsers());
    }//GEN-LAST:event_verr_buttonActionPerformed

    private void retour_prop_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour_prop_buttonActionPerformed
        general_panel.setVisible(true);
        panel_trois_boutton.setVisible(true);
        panel_verrouil.setVisible(false);
        panel_verrouil.setVisible(false);
        general_panel.removeAll();
        general_panel.repaint();
        general_panel.revalidate();
        general_panel.add(panel_trois_boutton);
        general_panel.repaint();
        general_panel.revalidate();
    }//GEN-LAST:event_retour_prop_buttonActionPerformed

    private void free_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_free_buttonActionPerformed
        general_panel.setVisible(true);
        panel_trois_boutton.setVisible(false);
        panel_verrouil.setVisible(false);
        free_gestion.setVisible(true);
        general_panel.removeAll();
        general_panel.repaint();
        general_panel.revalidate();
        general_panel.add(free_gestion);
        general_panel.repaint();
        general_panel.revalidate();
    }//GEN-LAST:event_free_buttonActionPerformed

    private void prop_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prop_buttonActionPerformed
        general_panel.setVisible(true);
        panel_trois_boutton.setVisible(false);
        panel_verrouil.setVisible(false);
        free_gestion.setVisible(false);
        panel_prop.setVisible(true);
        prop_verrou.setVisible(false);
        general_panel.removeAll();
        general_panel.repaint();
        general_panel.revalidate();
        general_panel.add(panel_prop);
        general_panel.repaint();
        general_panel.revalidate();
    }//GEN-LAST:event_prop_buttonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        prop_verrou.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void table3_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3_1MouseClicked
         int row = table3_1.getSelectedRow();
        id_text_prop.setText(table3_1.getModel().getValueAt(row, 0).toString());
        prenom_text_prop.setText(table3_1.getModel().getValueAt(row, 1).toString());   
        nom_text_prop.setText(table3_1.getModel().getValueAt(row, 2).toString());
        email_text_prop.setText(table3_1.getModel().getValueAt(row, 3).toString());   
        pays_text_prop.setText(table3_1.getModel().getValueAt(row, 4).toString());
        ville_text_prop.setText(table3_1.getModel().getValueAt(row, 5).toString());   
        login_text_prop.setText(table3_1.getModel().getValueAt(row, 6).toString());
        pwd_text_prop.setText(table3_1.getModel().getValueAt(row, 7).toString());
        entrp_text_prop.setText(table3_1.getModel().getValueAt(row, 7).toString());
        statut_text_prop.setText(table3_1.getModel().getValueAt(row, 9).toString());
    }//GEN-LAST:event_table3_1MouseClicked

    private void supprime_propActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprime_propActionPerformed
       
        Iproprietairedao freedao=new proprietairedao();
        String id=id_text_prop.getText();
        String prenom=prenom_text_prop.getText();
        String nom=nom_text_prop.getText();
        String email=email_text_prop.getText();
        String pays=pays_text_prop.getText();
        String ville=ville_text_prop.getText();
        String login=login_text_prop.getText();
        String pwd=pwd_text_prop.getText();
        String statut=statut_text_prop.getText();
        String entre=entrp_text_prop.getText();
        proprietaire free = new proprietaire();
        int idr=Integer.parseInt(id);
        free.setId(idr);
        free.setPrenom(prenom);
        free.setNom(nom);
        free.setEmail(email);
        free.setPays(pays);
        free.setVille(ville);
        free.setLogin(login);
        free.setPwd(pwd);
        free.setStatut(statut);
        free.setEntrep(entre);
        freedao.delete(free);
        table3_1.setModel(new Listprop());
    }//GEN-LAST:event_supprime_propActionPerformed

    private void dev_propActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dev_propActionPerformed
         Iproprietairedao freedao=new proprietairedao();
        String id=id_text_prop.getText();
        String prenom=prenom_text_prop.getText();
        String nom=nom_text_prop.getText();
        String email=email_text_prop.getText();
        String pays=pays_text_prop.getText();
        String ville=ville_text_prop.getText();
        String login=login_text_prop.getText();
        String pwd=pwd_text_prop.getText();
        String entrep=entrp_text_prop.getText();
        String statut=statut_text_prop.getText();
        int idr=Integer.parseInt(id);
        proprietaire free = new proprietaire(idr, prenom, nom, email, pays, ville, login, pwd, entrep, statut);
        freedao.update_actif(free);
        table3_1.setModel(new Listprop());
    }//GEN-LAST:event_dev_propActionPerformed

    private void verr_propActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verr_propActionPerformed
        
        Iproprietairedao freedao=new proprietairedao();
        String id=id_text_prop.getText();
        String prenom=prenom_text_prop.getText();
        String nom=nom_text_prop.getText();
        String email=email_text_prop.getText();
        String pays=pays_text_prop.getText();
        String ville=ville_text_prop.getText();
        String login=login_text_prop.getText();
        String pwd=pwd_text_prop.getText();
        String entrep=entrp_text_prop.getText();
        String statut=statut_text_prop.getText();
        int idr=Integer.parseInt(id);
        proprietaire free = new proprietaire(idr, prenom, nom, email, pays, ville, login, pwd, entrep, statut);
        freedao.update_nonactif(free);
        table3_1.setModel(new Listprop());
    }//GEN-LAST:event_verr_propActionPerformed

    private void pwd_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwd_adminActionPerformed

    private void email_recepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_recepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_recepActionPerformed
 public String cleanUrl(String s){

                //String s = url.toString();
                System.out.println("Before Clean");
                System.out.println(s);
                String delims = "/";
                String[] tokens = s.split(delims);
                System.out.println("After Clean");
                String mailPart="";
                for (int i=1;i<tokens.length;i++){
                    mailPart+=tokens[i]+"\\\\";
                }
                System.out.println(mailPart);
                return mailPart;
}
    private void envoie_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envoie_buttonActionPerformed
       String to =email_recep.getText();
        String password = pwd_admin.getText();
        String from = email_admin.getText();
        String subject = sujet.getText();
        String message=msg.getText();
 
        String file = cleanUrl(piece_jointe.getText());
        //String file = jLabelpieceJointe.getText();
        //System.out.println(jTextArearObject.getToolTipText());
        
        SendEmail send=new SendEmail();
      //  mc.getMailProperties();
        
       // String s = this.cleanUrl(url);
       // mc.getMailMessage(s, mail);
        send.send(to, subject, to, file, from, password);
        
         Mail mail = new Mail();
         
        mail.setMailAddressSender(from);
        mail.setMailAddressRecipient(to);
        mail.setMailSubject(subject);
        mail.setMailObject(message);
        mail.setPiecejointe(file);
        
        
        ImailDAO mailDao= MailDAO.getInstance();
        mailDao.envoyerEmail(mail);
    
        
    }//GEN-LAST:event_envoie_buttonActionPerformed

    private void chos_fichier_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chos_fichier_buttonActionPerformed
          JFileChooser chooser = new JFileChooser();
        int option = chooser.showOpenDialog(null);
       if(option == JFileChooser.APPROVE_OPTION){
            try{
              url = chooser.getSelectedFile().toURL();
               System.out.println(url);
             piece_jointe.setText(url.toString());
               
            }
          catch(MalformedURLException exception){
            System.out.println("The URL was malformed ... ");
              
            }
        }
    
    }//GEN-LAST:event_chos_fichier_buttonActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       IProposition ipro=new PropositionDAO();
       Proposition prop =new Proposition();
       int x=Integer.parseInt(prop1.getText());
       prop=ipro.findById(x);
       JOptionPane.showMessageDialog(null,prop.getId());
       String ch="Valide";
       prop.setStatut(ch);
        ipro.update(prop);
       table2.setModel(new ListProposition());

    }//GEN-LAST:event_jButton9ActionPerformed

    private void prop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prop1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prop1ActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        int row = table2.getSelectedRow();
        prop1.setText(table2.getModel().getValueAt(row, 0).toString());
        prop2.setText(table2.getModel().getValueAt(row, 1).toString());   
        prop3.setText(table2.getModel().getValueAt(row, 2).toString());
        stat.setText(table2.getModel().getValueAt(row, 3).toString());    
    }//GEN-LAST:event_table2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administrateur_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administrateur_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administrateur_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administrateur_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administrateur_interface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter_button;
    private javax.swing.JButton chos_fichier_button;
    private javax.swing.JButton dev_prop;
    private javax.swing.JTextField email_admin;
    private javax.swing.JTextField email_recep;
    private javax.swing.JTextField email_text;
    private javax.swing.JTextField email_text_prop;
    private javax.swing.JTextField entrp_text_prop;
    private javax.swing.JButton envoie_button;
    private javax.swing.JButton free_button;
    private javax.swing.JPanel free_gestion;
    private javax.swing.JPanel general_panel;
    private javax.swing.JTextField id_text;
    private javax.swing.JTextField id_text_prop;
    private javax.swing.JTextField idcat;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField login_text;
    private javax.swing.JTextField login_text_prop;
    private javax.swing.JButton modifier_button;
    private javax.swing.JTextArea msg;
    private javax.swing.JTextField nom_cat;
    private javax.swing.JTextField nom_text;
    private javax.swing.JTextField nom_text_prop;
    private javax.swing.JButton oui_button;
    private javax.swing.JPanel panel_prop;
    private javax.swing.JPanel panel_trois_boutton;
    private javax.swing.JPanel panel_verrouil;
    private javax.swing.JTextField pays_text;
    private javax.swing.JTextField pays_text_prop;
    private javax.swing.JLabel piece_jointe;
    private javax.swing.JTextField prenom_text;
    private javax.swing.JTextField prenom_text_prop;
    private javax.swing.JTextField prop1;
    private javax.swing.JTextField prop2;
    private javax.swing.JTextField prop3;
    private javax.swing.JButton prop_button;
    private javax.swing.JPanel prop_verrou;
    private javax.swing.JTextField pwd_admin;
    private javax.swing.JTextField pwd_text;
    private javax.swing.JTextField pwd_text_prop;
    private javax.swing.JButton retour_button;
    private javax.swing.JButton retour_prop_button;
    private javax.swing.JTextField stat;
    private javax.swing.JTextField statut_text;
    private javax.swing.JTextField statut_text_prop;
    private javax.swing.JTextField sujet;
    private javax.swing.JButton supprime_button;
    private javax.swing.JButton supprime_prop;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTable table3_1;
    private javax.swing.JTextField type_cat;
    private javax.swing.JButton ver_button;
    private javax.swing.JButton verr_button;
    private javax.swing.JButton verr_prop;
    private javax.swing.JTextField ville_text;
    private javax.swing.JTextField ville_text_prop;
    // End of variables declaration//GEN-END:variables
}
